### PR TITLE
Changing Set_type from bool to char for performance improvement

### PR DESCRIPTION
**Pull request by porya-gohary**

### CODE REVIEW

**Review by gnelissen — CHANGES_REQUESTED** [review]
add #ifdef to use vector<char> only for platforms where vector<bool> is not transformed in a bitset

**Comment by brandenburg** [comment]
Out of curiosity, on which platforms do you find the `vector<bool>` specialization to be missing?

**Comment by porya-gohary** [comment]
> Out of curiosity, on which platforms do you find the `vector<bool>` specialization to be missing?

I tested it with Linux with two different version of gcc: 11.4 and 12.3.

**Comment by gnelissen** [comment]
> Out of curiosity, on which platforms do you find the `vector<bool>` specialization to be missing?


we're not sure it is really the specialization that is missing, but at least vector< bool > generates very large performance degradations on our setup in Linux. We stumbled on it a few days ago when Porya's results in terms of runtime differed from mine in our last tests.

**Comment by brandenburg** [comment]
Oh, really? That's very strange. `g++` should know how to compile bool vectors efficiently. It might be helpful to do some profiling runs to identify the bottleneck that's the root cause (e.g., is it that worse instruction streams are emitted by the compiler, or does it trigger a bottleneck in the allocator, or something else entirely?). 

One thing to keep in mind is the memory impact this might have.

**Pull request closed without merging**
